server:
  port: 8081
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # auto-route via Eureka
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: download-service
          uri: lb://DOWNLOAD-SERVICE
          predicates:
            - Path=/download/**
          filters:
            - StripPrefix=1   # remove /download before forwarding
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes  # include 'routes' to see gateway routes