server:
  port: 8081
spring:
  application:
    name: api-gateway
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # auto-route via Eureka
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: download-service
          uri: lb://DOWNLOAD-SERVICE
          predicates:
            - Path=/download/**
