server:
  port: 8082
spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation=true:
  datasource:
    url: jdbc:postgresql://localhost:5433/testprac
    username: postgres
    password: 1991
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
